### ISSUE TITLE
Feedback in getting a specific code to work.

### ISSUE THREAD

**Issue by paaljoachim** [sheabunge/code-snippets#132] opened 2022-07-04 03:46 UTC
**Describe the bug**

Current problem: All the success update e-mails that show up when a plugin has been automatically updated.

Code solution:
```
add_filter( 'auto_plugin_update_send_email', 'plugin_update_email_on_failure', 10, 2 );

/**
 * Sends plugin update emails only when at least one plugin update has failed.
 *
 * @param bool  $enabled        Whether the plugin update email is enabled.
 * @param array $update_results An array of update results.
 * @return bool
 */
function plugin_update_email_on_failure( $enabled, $update_results ) {
	foreach ( $update_results as $update_result ) {
		if ( true !== $update_result->result ) {
			return true;
		}
	}
    return false;
}
```

Making WordPress slack:
Core-auto-updates channel.
https://wordpress.slack.com/archives/CULBN711P/p1656468319331729

**To Reproduce**
1. Test the above code snippet.
2. I did not get it to work.
3. See the above Slack link for the discussion regarding the code.

**Expected behavior**
I expected the code snippet to work.

**Screenshots**
See the slack channel link.

**Comment by sheabunge** [comment] 2022-07-22 08:19
Duplicate of #139.

**Closed by sheabunge** 2022-07-22 08:19 UTC
Labels: discussion
